stages:
  - "test"
  - "build"
  - "image"

test code:
  stage: test
  tags: ["docker"]
  image: golang:1.16.6-buster
  script: make test

build binary:
  stage: build
  tags: ["docker"]
  image: golang:1.16.6-buster
  script: make build
  artifacts:
    untracked: false
    expire_in: 1 days
    paths:
      - "bin/kube-oidc-proxy-linux"

build image:
  stage: image
  tags: ["dind"]
  script:
    - make image
    - docker tag kube-oidc-proxy:latest $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker login $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker rmi $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG kube-oidc-proxy:latest
